### ISSUE TITLE
MissingPluginException(No implementation found for method light on channel flutter_statusbar_text_color)

### ISSUE THREAD

**Issue by ghenry** [OPY-bbt/flutter_statusbar_text_color#2]
Hi,

I'm doing:

`FlutterStatusbarTextColor.setTextColor(FlutterStatusbarTextColor.light);`

and get:

```
I/flutter (14836): Caught error: MissingPluginException(No implementation found for method light on channel flutter_statusbar_text_color)
I/flutter (14836): stackTrace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter (14836): <asynchronous suspension>
I/flutter (14836): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (14836): #2      FlutterStatusbarTextColor.setTextColor (package:flutter_statusbar_text_color/flutter_statusbar_text_color.dart:11:20)
I/flutter (14836): #3      _HomeMasterState.initState (package:SureVoIPTalk/src/view/home.dart:55:31)
I/flutter (14836): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
I/flutter (14836): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (14836): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (14836): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (14836): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (14836): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (14836): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:
```

What am I missing here?

**Comment by marcscherer** [comment]
same here

**Comment by filly82** [comment]
same here. at least on android. on iOS it works
